# Generated by Django 5.1 on 2026-06-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('INTERNSHIP', 'Internship'), ('FREELANCE', 'Freelance'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=50),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
