# Generated by Django 5.1 on 2026-06-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='base',
            field=models.CharField(default='Digital Nebula 0x4', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='core_skill',
            field=models.CharField(default='Celestial Neobrutalism', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(default='The Architect', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='weapon',
            field=models.CharField(default='Modern Frontend & Shaders', max_length=100),
        ),
    ]
